[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "7hCML4igja81mLakZttsUuhPshhrYjZTqVSwEHWLCgTh"
logs = "JD4YNTouRS9Fqh3u7Vhq8RrJsXEVbEXAYdRM5Eqan7b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
